[WIP] Add robot deploy infrastructure
wpilibsuite/sysid pull request #157
Opened 2021-06-04 00:46 UTC by prateekma

2021-06-04 00:50 UTC, prateekma commented on sysid-application/src/main/native/cpp/view/Generator.cpp
> +      m_deploySession = DeploySession::Acquire(lp, *m_pTeam, true, wpi::json{},
Need to split acquire and exec because this does not run on UI thread.

2021-06-06 18:51 UTC, calcmogul requested changes

2021-06-06 18:51 UTC, calcmogul commented on sysid-application/src/main/native/cpp/Util.cpp
> +  ostream.flush();
The destructor automatically flushes the file, so the call to flush here is redundant.
```cpp
raw_fd_ostream::~raw_fd_ostream() {
  if (FD >= 0) {
    flush();
    if (ShouldClose && ::close(FD) < 0)
      error_detected(std::error_code(errno, std::generic_category()));
  }
```

2021-06-06 19:14 UTC, calcmogul submitted a review, later dismissed

2021-06-07 01:44 UTC, merged