Add Generator Config Saving and Loading
wpilibsuite/sysid pull request #166
Opened 2021-07-04 16:33 UTC by Piphi5

Users can now save their config files and load them again in the generator

2021-07-04 16:43 UTC, calcmogul commented on sysid-application/src/main/native/cpp/view/Generator.cpp
> +#include <wpi/span.h>
Is this code actually using wpi::span?

2021-07-04 16:44 UTC, calcmogul commented on sysid-application/src/main/native/cpp/generation/ConfigManager.cpp
> +    if (json_file.find(std::string(key)) == json_file.end()) {
Does `find()` not have a std::string_view overload?

2021-07-04 17:16 UTC, Piphi5 commented on sysid-application/src/main/native/cpp/view/Generator.cpp
> +#include <wpi/span.h>
No it's not.

2021-07-04 19:52 UTC, prateekma requested changes

2021-07-04 19:52 UTC, prateekma commented on sysid-application/src/main/native/cpp/generation/ConfigManager.cpp
> +          "{} was not present in config file. Please check its formatting",
Add period at end of sentence.

2021-07-08 01:32 UTC, calcmogul approved these changes

2021-07-10 00:46 UTC, prateekma approved these changes

2021-07-10 00:46 UTC, merged