Remove position measurement delay
wpilibsuite/sysid pull request #173
Opened 2021-08-20 04:14 UTC by Piphi5

Fixes #172

2021-08-20 05:58 UTC, calcmogul requested changes

2021-08-20 05:58 UTC, calcmogul commented on sysid-application/src/main/native/include/sysid/analysis/FeedbackControllerPreset.h
>    /** The measurement delay in the velocity measurements. */
Remove `velocity` from comment?

2021-08-20 20:24 UTC, calcmogul approved these changes

2021-08-24 13:30 UTC, prateekma approved these changes

2021-08-24 13:30 UTC, merged