Fix deployed JSON generation
wpilibsuite/sysid pull request #176
Opened 2021-08-24 07:26 UTC by Piphi5

The initializer list constructor of the json library causes config jsons
to be converted into an array type causing issues when reading it on the
rio. Tests have been added to ensure this won't happen.

2021-08-24 13:31 UTC, prateekma requested changes

2021-08-24 13:31 UTC, prateekma commented on sysid-application/src/main/native/include/sysid/deploy/DeploySession.h
> +  wpi::json GetJSON() const { return m_config; }
Can we just use const-reference here?

2021-08-24 13:31 UTC, prateekma commented on sysid-application/src/test/native/cpp/deploy/DeployJSONTest.cpp
> +  auto json = m_session.GetJSON();
Change to `const auto&` if above change is made.

2021-08-24 15:15 UTC, Piphi5 commented on sysid-application/src/main/native/include/sysid/deploy/DeploySession.h
> +  wpi::json GetJSON() const { return m_config; }
Yeah that's probably best

2021-08-25 15:50 UTC, prateekma approved these changes

2021-08-25 15:51 UTC, merged