Fix general mechanism config loading
wpilibsuite/sysid pull request #207
Opened 2021-11-13 01:17 UTC by calcmogul

The gyro type is saved as "AnalogGyro", but the arrays used for config
loading expect "Analog".

2021-11-13 01:19 UTC, calcmogul commented
Configs exported with the wrong value can be loaded by changing the JSON's "gyro" value from "AnalogGyro" to "Analog".

2021-11-13 01:27 UTC, Piphi5 commented
Wouldn't AnalogGyro be clearer and so we should update the Robot code?

2021-11-13 01:39 UTC, calcmogul commented
The class names don't line up for others either:

|GUI|Constructor name|
|---|----------------|
|Analog|AnalogGyro|
|NavX|AHRS|

2021-11-13 01:41 UTC, calcmogul commented
We should consider refactoring this to not use strings so it's less error-prone, but I don't know what that would look like.

2021-11-13 02:06 UTC, Piphi5 commented
Personally, I think AnalogGyro would be clearer in the GUI instead of passing it as Analog.

2021-11-13 02:08 UTC, Piphi5 commented
> We should consider refactoring this to not use strings so it's less error-prone, but I don't know what that would look like.
If we setup the #195 tests we wouldn't have to worry about it as much.

2021-11-13 02:13 UTC, calcmogul commented
> Maybe to not use strings we could also save the string in the json (for clarity) but also send a number that is mapped out to the right gyro in some file that's compiled with both the application and the project.

That sounds more complicated than what we're doing now.

2021-11-13 02:35 UTC, Piphi5 commented
Yeah it is. I think resolving #195 should fix things.

2021-11-13 17:03 UTC, Piphi5 commented
@calcmogul shouldn't the PR be titled "Fix Drivetrain config loading" or "Fix config loading"

2021-11-13 17:17 UTC, Piphi5 commented
Also, I just realized I misinterpreted the issue. We could create enums with String representations then have methods to convert between them similar to how the [analyzer](https://github.com/wpilibsuite/sysid/blob/main/sysid-application/src/main/native/include/sysid/analysis/AnalysisType.h) differentiates between different mechanism types.

2021-11-13 18:23 UTC, Piphi5 requested changes
Keep "AnalogGyro", update the other arrays to store that instead.

2021-11-13 22:17 UTC, Piphi5 approved these changes

2021-11-16 16:28 UTC, calcmogul commented
Superseded by #211.

2021-11-16 16:28 UTC, closed without merging