Split Gearing into numerator and denominator
wpilibsuite/sysid pull request #229
Opened 2021-11-28 21:46 UTC by Piphi5

2021-11-29 21:50 UTC, Piphi5 reviewed
Needs to do the same for the Analyzer gearing

2021-11-29 22:01 UTC, Piphi5 commented
Sorry wrong branch

2021-11-30 02:06 UTC, calcmogul requested changes

2021-11-30 02:06 UTC, calcmogul commented on sysid-application/src/main/native/cpp/view/Generator.cpp
> +  }
We should do this check for the numerator as well since a zero or negative value won't do sane things either.

2021-12-03 05:55 UTC, calcmogul commented on sysid-application/src/main/native/cpp/view/Generator.cpp
> +  }
Flip the order of these since everywhere else uses numerator then denominator.

2021-12-03 06:18 UTC, calcmogul approved these changes

2021-12-04 23:06 UTC, merged