Add REVLib to 2022
wpilibsuite/sysid pull request #235
Opened 2021-12-03 04:12 UTC by Piphi5

2021-12-03 06:21 UTC, calcmogul requested changes

2021-12-03 06:21 UTC, calcmogul commented on sysid-library/src/main/include/sysid/generation/SysIdSetup.h
> +    std::unique_ptr<rev::SparkMaxAlternateEncoder>& revDataPort,
The non-owning version of `std::unique_ptr<T>` is `T*`, not `std::unique_ptr<T>&`.

2021-12-03 07:05 UTC, calcmogul commented on sysid-library/src/main/include/sysid/generation/SysIdSetup.h
> +    std::unique_ptr<rev::SparkMaxAlternateEncoder>& revDataPort,
Nevermind. This is an out parameter, not an in parameter.

2021-12-04 23:01 UTC, calcmogul requested changes

2021-12-04 23:01 UTC, calcmogul commented on sysid-library/src/main/include/sysid/generation/SysIdSetup.h
>   *                        (doesn't apply to NEO Integrated Encoders)
Indent the line continuations past the parameter name.

2021-12-04 23:16 UTC, calcmogul submitted a review, later dismissed

2021-12-06 01:27 UTC, prateekma approved these changes

2021-12-06 01:27 UTC, merged