Add ADIS gyros
wpilibsuite/sysid pull request #242
Opened 2021-12-05 22:33 UTC by Piphi5

2021-12-31 05:11 UTC, calcmogul commented
The development build that includes the ADIS classes finally published, so this PR can start using them.

2022-01-03 20:01 UTC, calcmogul requested changes

2022-01-03 20:01 UTC, calcmogul commented on README.md
> +- ADIS Gyro
```suggestion
- ADIS16448 IMU
- ADIS16470 IMU
```

2022-01-03 20:01 UTC, calcmogul commented on README.md
>  - Analog Gyro
Are these in any particular order?

2022-01-03 20:17 UTC, Piphi5 commented on README.md
>  - Analog Gyro
Not really, should we alphabetize it?

2022-01-03 20:33 UTC, calcmogul commented on README.md
>  - Analog Gyro
Yea

2022-01-03 20:53 UTC, calcmogul requested changes

2022-01-03 20:53 UTC, calcmogul commented on sysid-library/src/main/cpp/generation/SysIdSetup.cpp
> +    throw std::runtime_error(fmt::format("{} is not a supported SPI Port\n"));
You forgot to put the name as a format argument.

2022-01-03 21:05 UTC, calcmogul approved these changes

2022-01-03 21:24 UTC, merged