Remove CTRE ifdef code for integration tests
wpilibsuite/sysid pull request #256
Opened 2021-12-19 05:32 UTC by Piphi5

2021-12-19 05:33 UTC, Piphi5 commented
Waiting on #255 to be merged

2021-12-21 20:01 UTC, calcmogul commented
The commit message should also mention there's changes to some function arguments to fix lifetime issues. Ideally, that would be in a separate commit.

2021-12-21 20:37 UTC, calcmogul commented
You should do an interactive rebase with each commit set to "edit" so you can check each commit compiles. That should help you track down the build issue.

2021-12-22 06:56 UTC, calcmogul requested changes

2021-12-22 06:56 UTC, calcmogul commented on sysid-projects/mechanism/src/main/cpp/Robot.cpp
> -#ifdef INTEGRATION
This #ifdef shouldn't be removed.

2021-12-23 06:34 UTC, calcmogul approved these changes

2021-12-23 15:20 UTC, merged