Fix CTRE Feedback Controller Presets
wpilibsuite/sysid pull request #273
Opened 2021-12-28 05:58 UTC by Piphi5

Fixes #272

2021-12-28 05:58 UTC, Piphi5 commented on sysid-application/src/main/native/include/sysid/analysis/FeedbackControllerPreset.h
> +                                                81.5_ms};
Could someone verify that these are the proper settings for the two different types?

2021-12-29 08:36 UTC, prateekma requested changes

2021-12-29 08:36 UTC, prateekma commented on sysid-application/src/main/native/include/sysid/analysis/FeedbackControllerPreset.h
> +constexpr FeedbackControllerPreset kCTREDefault{1024.0 / 12.0, 0.1, 1_ms, false,
This should be 1023

2022-01-03 20:22 UTC, calcmogul approved these changes

2022-01-03 20:50 UTC, merged