Display right and left datasets
wpilibsuite/sysid pull request #362
Opened 2022-02-07 23:53 UTC by Piphi5

Fixes #361

2022-02-08 16:32 UTC, calcmogul requested changes

2022-02-08 16:32 UTC, calcmogul commented on sysid-application/src/main/native/cpp/analysis/AnalysisManager.cpp
> +  filteredDataset[0] = CombineDatasets(
The enum should be used here instead of a magic number.

2022-02-09 03:59 UTC, calcmogul commented
Do you have a dataset I can test this PR against?

2022-02-09 05:22 UTC, Piphi5 commented
Here are the datasets I used to double check. Granted, the drivetrain one isn't great but it at least showed that the values were different for the different datasets. And the other dataset I used to make sure it works fine for non-drive datasets.
Drivetrain:
[sysid_data20220122-085328.json.txt](https://github.com/wpilibsuite/sysid/files/8029639/sysid_data20220122-085328.json.txt)

Other:
[sysid_data20220114-202020.json.txt](https://github.com/wpilibsuite/sysid/files/8029641/sysid_data20220114-202020.json.txt)

2022-02-09 07:33 UTC, calcmogul approved these changes

2022-02-09 07:33 UTC, merged